### ISSUE TITLE
Document saved but DocNo in brackets remain

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#101]
Document is saved but DocNo in brackets remain
- this should not. it shall only remain the DocNo in Breadcrumb + BPartner name + documentdate + grandtotal (for Order)
- please also check in case of cache reset, if for "old" documents these informations above are shown. seems as if they "dissappea".
![image](https://cloud.githubusercontent.com/assets/13365687/21351163/66ffe6a2-c6bb-11e6-86c4-7c90aba6bbf4.png)

**Comment by teosarca** [comment]
cannot reproduce anymore.
