### ISSUE TITLE
Quick input layout is not returning anything.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui#103]
It stopped working after rollout on tuesday this week. When i try to get layout http://w101.metasfresh.com:8081/rest/api/window/143/1003070/1/quickInput/layout there is no response - so there is no posibility to render quick input.

**Comment by teosarca** [comment]
fixed by https://github.com/metasfresh/metasfresh-webui/commit/fd655e044aa7389e2aab33db2e28e4efd2bcdda5
