### ISSUE TITLE
Order line quick input shall automatically set the default Packing item if available

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#111]

**Comment by metas-lc** [comment]
created follow-up task: https://github.com/metasfresh/metasfresh-webui/issues/112

**Comment by teosarca** [comment]
@metas-lc  then i think we can close this one, right?

**Comment by metas-rc** [comment]
Results of IT1: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23111.md OK
