### ISSUE TITLE
orderline quick input follow-up

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui#112]
- sales order: 
* batch entry - adding same product multiple times: once i get the product with HU (e.g. HU x 10), once with "No Handling Unit"  NOK
* add new - orderline takes the one from trading unit field (trading unit field is virtual pi by default - won't change, but i think this field should not be here) NOK
* batch entry when is no HU for the product+bpartner - once with "No Handling Unit", one with "Virtual PI" NOK

- purchase order:
*  batch entry - adding same product multiple times: you will always get the HU set on product (e.g. HU x 10), even if the HU is for another bpartner NOK
*  add new seems to work fine OK
* not sure if wanted, but trading unit field is not shown in purchase order line NOK?

**Comment by teosarca** [comment]
NOTE: you can see "No Handling Unit" in results because there is a packing item which is called like that, a different one from the actual "No Handling Unit".

See https://github.com/metasfresh/metasfresh/issues/960

**Comment by metas-rc** [comment]
Followup created: https://github.com/metasfresh/metasfresh-webui/issues/128

**Comment by metas-rc** [comment]
Results of IT 1:

Tested together with https://github.com/metasfresh/metasfresh-webui/issues/111, same test cases: 
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23111.md OK

**Comment by metas-rc** [comment]
Followup created: https://github.com/metasfresh/metasfresh-webui/issues/129
