### ISSUE TITLE
qty 0 in purchase order

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui#116]
go to purchase order window, create a new one and use batch entry to add a new product: add product P0001 with HU01 and set a quantity >0 => in the line the qty is set to 0. NOK

**Comment by metas-mk** [comment]
Also reproducible in Sales Order Window. Entered "Convenience Salad" + No Handling Unit Qty 10. In the Line the qty 0 is recorded.
![image](https://cloud.githubusercontent.com/assets/13365687/22854127/6312b9a4-f067-11e6-9c4b-7d100e529933.png)

**Comment by teosarca** [comment]
shall be fixed in https://github.com/metasfresh/metasfresh-webui-frontend/issues/276

**Comment by teosarca** [comment]
update: atm we are just throwing an exception if the Qty is zero

**Comment by metas-mk** [comment]
Tested. Works nicely now.
