### ISSUE TITLE
Dropdown for Pricelist Version in Product>Price Subtab remains empty

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#117]
Dropdown for Pricelist Version in Product>Price Subtab remains empty
- how to reproduce. go to product window window/140/. select an existing product. Add new to price (preis) subtab. click the dropdown for Pricelist Version.

![image](https://cloud.githubusercontent.com/assets/13365687/22592791/ae2c1f04-ea1b-11e6-9126-69d73abcfd46.png)

**Comment by teosarca** [comment]
frontend bug: https://github.com/metasfresh/metasfresh-webui-frontend/issues/249
shall be solved there.

**Comment by metas-dh** [comment]
Results of IT2

tested on w101: 
* Pricelist Version in Product>Price Subtab: Dropdown shows all available Pricelist Versions: OK
* selected Pricelist Version is set for new product price: OK
