### ISSUE TITLE
Functionality to easily add files to current record in webUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#118]
Functionality to easily add files to current record in webUI
Something like image elevator in WordPress. Just drag a file from desktop or explorer or clipboard and drop/ paste in metasfresh webUI.
--> the file is added to selected current record as an attachment.

**Comment by teosarca** [comment]
See: http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/attachFileUsingPOST

endpoint: /rest/api/window/{windowId}/{documentId}/attachments

**Comment by metas-mk** [comment]
Tested with 0 Byte size File. Does now not lead into divide by zero error.

**Comment by metas-mk** [comment]
Issue already included in Release Notes.
