### ISSUE TITLE
Error when Pressing the Attribute Button

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#119]
Error when pressing the Attribute Button

![image](https://cloud.githubusercontent.com/assets/13365687/22659172/f0870c3c-ec9c-11e6-8258-c60c445362b5.png)

**Comment by teosarca** [comment]
NOTE: could not reproduce it on current baseline => it will be fixed on next rollout

**Comment by metas-mk** [comment]
Quick Test. Works now.

**Comment by metas-mk** [comment]
Created ReleaseNotes for 4.45.55
