### ISSUE TITLE
Material Receipt WebUI: Attribute Values wrong

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#120]
Material Receipt WebUI: Attribute Values wrong
* shall show "" when empty and resovled content when selected e.g. County "D" is Deutschland/ Germany ...
![image](https://cloud.githubusercontent.com/assets/13365687/22874285/74dcdb38-f1c5-11e6-8307-0bb55cdcc826.png)

**Comment by teosarca** [comment]
NOTE: the "leer" or "none" is OK because that's how the UI tells the user that the field is empty/null.

**Comment by metas-mk** [comment]
Tested. Values are now resolved. Works nicely.

**Comment by metas-mk** [comment]
Added to Release Notes.
