### ISSUE TITLE
Empties Returns for Vendors and Customers in Material Receipt Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#121]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
Currently, it is not possible to do Vendor and Customer Returns for Empties in WebUI.
### What is the expected or desired behavior?
Have a functionality in Material Receipt Candidates Window in Web User Interface to do Empties return. 2 Actions (1 for Vendor, 1 for Customer). The action shall open a generic window for Vendor/ Customer Returns Document with already set Business partner and Location. The user then just has to press Batch recording and enter the needed Packaging Material.

**Comment by teosarca** [comment]
to be integrated after https://github.com/metasfresh/metasfresh/issues/942

**Comment by teosarca** [comment]
UPDATE: cherry-picked everything from "gh121-webui" branch to "gh121-webui-2" branch.

**Comment by teosarca** [comment]
https://github.com/metasfresh/metasfresh/pull/965
https://github.com/metasfresh/metasfresh-webui/pull/125

**Comment by metas-lc** [comment]
IT. OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23121.md
