### ISSUE TITLE
Material receipt webui: Implement "Correct" action

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#122]
The action shall open the HU editor with currently received HUs of selected receipt schedule.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101:
* "Correct" opens HU Editor with all HUs already received: OK
* Selecting HUs and clicking "Correct" action: selected HUs disappear, OK
* Qty moved in the receipt line is reduced after "Correct", but only after refreshing the page: NOK

**Comment by teosarca** [comment]
> Qty moved in the receipt line is reduced after "Correct", but only after refreshing the page (caching problem): NOK

That problem shall be solved by #150 .

Besides that, everything looks OK, so i am closing this task.
