### ISSUE TITLE
Default/ Standard Filter not correct in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#124]
### Is this a bug or feature request?
Bug.
### What is the current behavior?
The Default Filter criteria are not shown in WebUI for a given window.
#### Which are the steps to reproduce?
Compare the default filter in WebUI for Business Partner Window with Filter/ Search criteria shown in Swing Client.
### What is the expected or desired behavior?
Have the same Search/ Filter criteria for Default/ Standard in both environments.

![image](https://cloud.githubusercontent.com/assets/13365687/22919843/6c301b76-f292-11e6-982c-ec546df90386.png)
![image](https://cloud.githubusercontent.com/assets/13365687/22919859/7f717054-f292-11e6-94f2-ad36ea325935.png)

**Comment by teosarca** [comment]
NOTE: on webui (compared with Swing UI) we decided to not consider Value,Name,DocumentNo fields as filters (by default). They shall be explicitly configured as AD_Column.IsSelectionColumn.
