### ISSUE TITLE
Error in shipment creation via shipment schedule

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#126]
### Is this a bug or feature request?
Bug.
### What is the current behavior?
Error occurs when starting the process for shipment creation in shipment schedule window.
#### Which are the steps to reproduce?
Start the shipment creation process in Shipment Schedule window.
### What is the expected or desired behavior?
Eliminate the bug so that the shipment can be created.
![image](https://cloud.githubusercontent.com/assets/13365687/22964700/39d7685a-f35a-11e6-9d5f-1ad4aec5f41d.png)

**Comment by metas-mk** [comment]
Same thing happens in Invoice Candidates Window when starting invoice generation process.
![image](https://cloud.githubusercontent.com/assets/13365687/22965071/0a284ec4-f35c-11e6-81da-adfd9b355321.png)

**Comment by teosarca** [comment]
remark that the error was "HTTP 400" (bad request) => frontend issue.

will be solved by https://github.com/metasfresh/metasfresh-webui-frontend/issues/297
