### ISSUE TITLE
Receipt schedules - Receive with configuration improvements

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#127]
* it shall correctly compute the initial QtyLU
* introduce a new flag called "Save configuration" => only then, the config. shall be saved to M_ReceiptSchedule.M_HU_LUTU_Configuration_ID => so it will be used as default for next receives.

**Comment by teosarca** [comment]
NOTE to IT:
* full regression test needed; focus on: receipt schedule's generated HUs, Wareneingang POS receiving using std configuration, using custom configuration

**Comment by teosarca** [comment]
helpful for testing:  query to check how the LU/TU config changed for a given receipt schedule line:

```
select
	c.M_HU_LUTU_Configuration_ID
	, rs.M_ReceiptSchedule_ID
	, luPI.Name as LU_PI
	, tuPI.Name as TU_PI
	, c.QtyLU
	, c.QtyTU
	, c.QtyCU
	, c.Updated
	, '-------'
	, c.*
--
-- from M_HU_LUTU_Configuration c
from M_ReceiptSchedule rs
left outer join M_HU_LUTU_Configuration c on (c.M_HU_LUTU_Configuration_ID=rs.M_HU_LUTU_Configuration_ID)

left outer join M_HU_PI luPI on (luPI.M_HU_PI_ID=c.M_LU_HU_PI_ID)
left outer join M_HU_PI tuPI on (tuPI.M_HU_PI_ID=c.M_TU_HU_PI_ID)
where true 
	-- and c.M_HU_LUTU_Configuration_ID>=1000002
	and rs.M_ReceiptSchedule_ID=1000003
order by c.Updated desc
limit 10
```

**Comment by metas-mk** [comment]
Tested. Works nicely.

**Comment by metas-mk** [comment]
Added to Release Notes.
