### ISSUE TITLE
Order Line Batch Entry not working for Packing Material Products/ Products with no TU

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#129]
### Is this a bug or feature request?

* Bug
### What is the current behavior?

* One cannot add an orderline for a Packing material product via batch entry
#### Which are the steps to reproduce?

* Create a Purchase or Sales Order
* Add a line with "Add New" 
* Select a packing material Product (e.g. G1)
* => OK It automatically has Virtual PI set as TU, the line is correctly created
* Try to add a line via batch entry
* Select the same Packing material product (e.g. G1)
* Select a qty, press enter
* => NOK: There is an error at the top-right saying: 
 " Error
Mandatory fields are not filled!" 

### What is the expected or desired behavior?

* Batch entry should also work, for packing paterial products, as Add new works.

Followup for https://github.com/metasfresh/metasfresh-webui/issues/112

**Comment by teosarca** [comment]
NOTE to IT: to be tested after https://github.com/metasfresh/metasfresh-webui-frontend/issues/322

**Comment by metas-rc** [comment]
Results of IT1:
Tested on http://w101.metasfresh.com:8090/
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23129.md OK
