### ISSUE TITLE
Receiving HUs: already received HUs shall be flagged as processed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#132]
Needed for https://github.com/metasfresh/metasfresh-webui-frontend/issues/277.

NOTE to IT: the tests shall be performed on frontend task because this one it's only technical.

**Comment by teosarca** [comment]
Introduced "processed" flag.
The flag is set only when it's "true" because we want to save bandwidth.

![image](https://cloud.githubusercontent.com/assets/1244701/23014907/89154e5c-f439-11e6-8f12-adf850b25edd.png)

**Comment by metas-mk** [comment]
Tested with chrome inspector. Selecting LU and receiving leads to all HU Levels to be set as "processed" Works nicely. Added to Release Notes.
