### ISSUE TITLE
process parameter defaults are not set

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui#135]
### Is this a bug or feature request?
bug
### What is the current behavior?
jasper report has ad_org_id set to none
#### Which are the steps to reproduce?
open "revenue business partner" jasper process. See ad_org_id. is readonly (wanted) but the default value is not set
### What is the expected or desired behavior?
open "revenue business partner" jasper process. See ad_org_id : filled with the one from context

**Comment by metas-lc** [comment]
![report](https://cloud.githubusercontent.com/assets/16001666/23028517/411ddc54-f470-11e6-941d-3520683b2e0d.png)

**Comment by metas-rc** [comment]
Results of IT1:

OK: Now the default Org is set on the default organization and read-only when opening the "Revenue business partner" jasper process. 


Open: I get this when running the report: 

> Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Sun Feb 19 17:46:20 CET 2017
> There was an unexpected error (type=Bad Request, status=400).
> Failed to convert value of type [java.lang.String] to required type [int]; nested exception is java.lang.NumberFormatException: For input string: "null"

**Comment by metas-rc** [comment]
UPDATE:
* Talked with Teo. It looks like a frontend problem but it's not high prio. Created this task as followup: https://github.com/metasfresh/metasfresh-webui/issues/153
