### ISSUE TITLE
Make sure ProcessInstance is not override by concurrent REST api call

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#137]
Test case:
* open Receive HUs process
* delete QtyTU (don't press enter or anything else)
* type a number in QtyTU (don't press enter or anything else)
* quickly click on "Save configuration" flag
* sometimes the changed QtyTU is not taken, and you can quickly remark that back in quick actions.

![image](https://cloud.githubusercontent.com/assets/1244701/23045921/7034afb0-f4af-11e6-9699-8f6839dc59e8.png)

In quick actions, the first action is the "Receive to <default config>". You can spot that the quantity TU was not changed in it's name. In the example below, we have 3 x G2.
![image](https://cloud.githubusercontent.com/assets/1244701/23046050/226e2b84-f4b0-11e6-9915-ec3057725bcd.png)

**Comment by metas-rc** [comment]
Results of IT1

Tested on http://w101.metasfresh.com:8090

I repeated the test and the config was always saved. OK
