### ISSUE TITLE
change name of new record button

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui#138]
have a way to change the name of the new record button:
![image](https://cloud.githubusercontent.com/assets/16079655/23064192/ce359d36-f50e-11e6-8f79-e0ccab2e6623.png)

current problem:
![image](https://cloud.githubusercontent.com/assets/16079655/23064161/a4b0c760-f50e-11e6-8bc9-ab6c12896987.png)

![image](https://cloud.githubusercontent.com/assets/16079655/23064180/c12c98e2-f50e-11e6-9653-623885d15c4d.png)

**Comment by teosarca** [comment]
Note to IT:
* a grid view shall display the "new record" button only if there is a node in menu which is flagged as "NewRecord", e.g. Neuer Auftrag
* make sure the webui menu is displayed using user's language. You can play with http://w101.metasfresh.com:8081/swagger-ui.html#!/user-session-rest-controller/setAD_LanguageUsingPUT_1 to change the current language

* reggression: make sure Swing menu is displayed (login with several languages)

**Comment by metas-mk** [comment]
Tested this issue implementation on Backend. Works nicely. Frontend side will be tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/345 as soon as implemented.
![image](https://cloud.githubusercontent.com/assets/13365687/23102896/e69031a8-f6b1-11e6-96d6-75907951aea1.png)
