### ISSUE TITLE
edit address not working anymore

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui#141]
click on edit address on any partner address and you get:

![image](https://cloud.githubusercontent.com/assets/16079655/23092998/889966e4-f5d7-11e6-9575-cb0448911090.png)

testcase:
http://w101.metasfresh.com:8090/window/123/2156496

**Comment by metasnw** [comment]
![image](https://cloud.githubusercontent.com/assets/16079655/23093522/62ba8944-f5e6-11e6-8846-7e6690779889.png)

**Comment by metas-mk** [comment]
Reproduced behavior in new Product Price Window window/540325/ w/ Attributes Editor too.
![image](https://cloud.githubusercontent.com/assets/13365687/23095222/9f9bcce0-f606-11e6-81a7-7a0e92ec408f.png)

**Comment by metas-mk** [comment]
Test was done. Checked in New Product Price window, Location subtab, and others. Works nicely now.

**Comment by teosarca** [comment]
NOTE: found the case & hotfixed. It was failing if "debugProtocol" was enabled (see http://w101.metasfresh.com:8081/swagger-ui.html#!/debug-rest-controller/setDebugProtocolUsingGET ).
