### ISSUE TITLE
HU editor - Create material receipt not enabled when the whole palet is selected

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#145]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
open HU editor with one palet, select all. The "create material receipt" quick action is not enabled.

(reason: the action is not enabled because the HU storage line is selected)

### What is the expected or desired behavior?
Be able to receipt in this case because it's a valid case.

**Comment by metas-mk** [comment]
Tested. Works nicely now.
