### ISSUE TITLE
Material Receipt Candidates not updated after receive HU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#150]
### Is this a bug or feature request?
Bug.
### What is the current behavior?
MMaterial Receipt Candidates quantities are not updated after receive,
#### Which are the steps to reproduce?
Window Material Receipt Candidates. Receive HU. When receiving HU in Handling Unit Editor and pressing done, then the received qty is not updated in Material Receipt candidates window.
### What is the expected or desired behavior?
Update the quantities when receiving and after correction. Other cases involved too?

**Comment by metas-rc** [comment]
Results of IT1

Tested on http://w101.metasfresh.com:8090/

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23150.md OK

**Comment by metas-mk** [comment]
Checked on w101 and others. Does not work 4me.

**Comment by teosarca** [comment]
possible frontend issues will be handled on https://github.com/metasfresh/metasfresh-webui-frontend/issues/387

**Comment by metas-rc** [comment]
Results of IT2: 

Tested on http://w101.metasfresh.com:8090/

Tests repeated. All worked fine for me. 
It would be ok to test it on a slower server again.

**Comment by metas-rc** [comment]
Results of IT 3 (GPRS setting)

Tested on http://w101.metasfresh.com:8090/

Repeated the tests with GPRS config and all went fine. OK
