### ISSUE TITLE
Error in invoice candidate enqueuing

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#155]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* Sometimes, when trying to invoice, you get an error like: 
![image](https://cloud.githubusercontent.com/assets/16001442/23123640/e67adafe-f771-11e6-9a98-fe31b96f6d96.png)

#### Which are the steps to reproduce?
* Create a sales order, complete it
* Go to the shipment schedule, create shipment
* Go back to the order, open its invoice candidates
* Call invoice creating process
* NOK: Sometimes you get the error above

### What is the expected or desired behavior?
* Invoicing should work with no error.

* The stacktrace is : 

> com.google.common.util.concurrent.ExecutionError: java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
>         at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
>         at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
>         at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
>         at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
>         at org.adempiere.images.Images.getImageIcon2(Images.java:189)
>         at org.compiere.apps.ADialogDialog.<clinit>(ADialogDialog.java:225)
>         at de.metas.adempiere.form.swing.SwingAskDialogBuilder.getAnswer(SwingAskDialogBuilder.java:84)
>         at de.metas.invoicecandidate.process.C_Invoice_Candidate_EnqueueSelection.checkPerformEnqueuing(C_Invoice_Candidate_EnqueueSelection.java:115)
>         at de.metas.invoicecandidate.process.C_Invoice_Candidate_EnqueueSelection.prepare(C_Invoice_Candidate_EnqueueSelection.java:94)
>         at de.metas.process.JavaProcess.prepareProcess(JavaProcess.java:423)
>         at de.metas.process.JavaProcess.startProcess(JavaProcess.java:134)
>         at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:559)
>         at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:457)
>         at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)
>         at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:220)
>         at org.adempiere.ad.trx.api.impl.AbstractTrxManager.runOutOfTransaction(AbstractTrxManager.java:911)
>         at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:276)
>         at de.metas.process.ProcessExecutor.lambda$executeSync$1(ProcessExecutor.java:143)
>         at java.lang.Thread.run(Thread.java:745)

Hint: 
	
* It happens when candidates of more than one partner are enqueued.
* See de.metas.invoicecandidate.process.C_Invoice_Candidate_EnqueueSelection.checkPerformEnqueuing()

**Comment by teosarca** [comment]
Note to IT: regression - make sure in swing is ok

**Comment by metas-rc** [comment]
Results of IT1

Tested on http://w101.metasfresh.com:8090/

I invoiced several candidates from several orders, also in parallel. I didn't get that problem any more. OK
