### ISSUE TITLE
View ID missing  in "Create material receipt" opened from single view

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#156]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* When trying to create material receipt for a receipt schedule opened in single view you get the following error

> {pinstanceId: 1243660, summary: "Fill mandatory fields: $WEBUI_ViewId", error: true}
> error
> :
> true
> pinstanceId
> :
> 1243660
> summary
> :
> "Fill mandatory fields:  $WEBUI_ViewId"

#### Which are the steps to reproduce?
* Create a purchase order, complete it
* Go to receipt schedule, select the product one, open in single view
* Receive HUs
* Run "Create material receipt".
* => NOK: You get the error above
### What is the expected or desired behavior?
* The material receipt should be created with no error

Hint: The view id is missing from the request. See

![receipt schedule singleview receive hus](https://cloud.githubusercontent.com/assets/16001442/23125719/d9b1687e-f77b-11e6-8384-f40bc28ea798.png)

**Comment by teosarca** [comment]
Frontend bug.
