### ISSUE TITLE
Button Action in Subtab for Price List Version creation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#161]
### Is this a bug or feature request?
Feature
### What is the current behavior?
Action for Price List Version Creation Missing in WebUI.
#### Which are the steps to reproduce?
Open Price List. Add a new Pricelist Version. Button for triggering the Product Price Creations are Missing.
### What is the expected or desired behavior?
Add Functionality to that button, if generic missing then pls add the generic Functionality and organize w/ webui-frontend.

![image](https://cloud.githubusercontent.com/assets/13365687/23135949/cdca48b8-f79a-11e6-8fb6-d839fb8b4860.png)

**Comment by teosarca** [comment]
Frpntend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/250

**Comment by metas-dh** [comment]
Results of IT 1

tested on w101:
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23161.md: OK
