### ISSUE TITLE
Possibility to choose used filter criteria for webUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#162]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
All Filter criteria are shown that are defined in metasfresh for a given window.
#### Which are the steps to reproduce?
Open Sales Order Window and press Filter button for migrated Database.
### What is the expected or desired behavior?
Have the possibility to mark the filter criteria that shall be shown for a user.

**Comment by metas-mk** [comment]
Quick workaround solution could be to restrict to filter criteria created by user_id = 100 atm. WDYT?

**Comment by metas-rc** [comment]
Will move to done only after this https://github.com/metasfresh/metasfresh-webui-frontend/issues/389 is solved.

**Comment by metas-rc** [comment]
Results of IT1: 

Tested on http://w101.metasfresh.com:8090/

This functionality works correctly.
TODO: a proper documentation file.
