### ISSUE TITLE
Menu search does not show all matching entries

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#163]
### Is this a bug or feature request?
Bug
### What is the current behavior?
In some conditions, the search in sitemap does not show all relevant results.
#### Which are the steps to reproduce?
In German Base Language open Sitemap. Search for "Rabatt". Although a window exists w/ that name, it's not returned as result.
### What is the expected or desired behavior?
Show all matching search results.
![image](https://cloud.githubusercontent.com/assets/13365687/23138945/68891730-f7aa-11e6-9c86-7c880d078e67.png)
![image](https://cloud.githubusercontent.com/assets/13365687/23138950/6c9de080-f7aa-11e6-858a-5a003fd1ceda.png)

**Comment by teosarca** [comment]
IMHO shall be solved in https://github.com/metasfresh/metasfresh-webui-frontend/issues/375
