### ISSUE TITLE
Handling Unit Editor first line initially selected: error no selection

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#169]
### Is this a bug or feature request?
Bug.
### What is the current behavior?
Although the first line is initially selected in Handling Unit, the user gets "NoSelection" error.
#### Which are the steps to reproduce?
Material Receipt Candidates. Do "Receive" via main action. Handling Unit Editor opens, the first row is initially selected. Now directly press <ctrl>u. The error pops up.
### What is the expected or desired behavior?
No error, selection shall be taken.
![image](https://cloud.githubusercontent.com/assets/13365687/23160377/82fb368a-f826-11e6-8b69-46ff9ed838d3.png)

**Comment by teosarca** [comment]
Can be reproduced on our IT server?
If yes, pls also check & attach the Inspect->Network log.
Check:
* which was the selectedIds when the quickActions was queried last time
* which is the request body when the process instance was created

**Comment by metas-lc** [comment]
i could reproduce (select a line in HU)
selectedIds:1003925

{processId: 540749, viewId: "de338301-7911-45c8-b959-fa0cbefbf3d5", viewDocumentIds: ["1003925"]}
processId:540749
viewDocumentIds:["1003925"]
0:"1003925"
viewId:"de338301-7911-45c8-b959-fa0cbefbf3d5"

**Comment by metas-lc** [comment]
![ctrlu](https://cloud.githubusercontent.com/assets/16001666/23205907/4c68129a-f8f4-11e6-8c72-69aba66549ca.png)

**Comment by metas-lc** [comment]
From Mark: the ctrl-u in documents = COmplete action
in non document windows (only have hu editor/ material receipt candidates atm) the main action "green button" is triggered

**Comment by teosarca** [comment]
Debugged. Not a backend bug.
Shall be solved by https://github.com/metasfresh/metasfresh-webui-frontend/issues/404

Pls read my comments there to understand what happened.
