### ISSUE TITLE
ElementId in node response.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui#17]
The navigation between windows is realized by elementId. When i get paths for windows in node, there is no elementId - and i should make another call to get that to navigate farther. 

Providing elementId '/menu/node?nodeId=' for this endpoint allows to save one additional call.

![screen shot 2016-09-12 at 08 54 29](https://cloud.githubusercontent.com/assets/5701744/18427142/88db8d96-78c6-11e6-8e95-a736feff8952.png)

**Comment by teosarca** [comment]
Not a bug. As discussed with @damianprzygodzki , nodes of type "group" does not have an elementId because there is none. All other types have.
