### ISSUE TITLE
No packing item selectable for M_HU_PI_Item_Product 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui#171]
### Is this a bug or feature request?
Bug
### What is the current behavior?
User cannot add M_HU_PI_Item_Product for a product
#### Which are the steps to reproduce?
* open window Product, select one
* in single view, select tab CU TU Zuordnung (M_HU_PI_Item_Product ), click Add new
* try selecting a packing item in Packvorschrift Position: read-only, nothing can be selected
### What is the expected or desired behavior?
the available packing items shall be selectable, so user can create a CU TU Zuordnung

**Comment by metas-lc** [comment]
IT:
* batch entry does not work, but we already have a task: https://github.com/metasfresh/metasfresh-webui/issues/175

1. open window Product, select one
2. in single view, select tab CU TU Zuordnung (M_HU_PI_Item_Product ), click Add new
=> fields are not readonly anymore: you can add a packing instruction, qty and so on.
OK
* valid from shall be mandatory, the same for qty/infinite capacity. NOK . Created follow-up: https://github.com/metasfresh/metasfresh-webui/issues/192
