### ISSUE TITLE
Entries skipped at the begining of pages

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#172]
### Type of issue
* Bug
### Current behavior
 * If you open a window with entries that are enough to fill more than one page, there is one entry  skipped at the change of each page
### Expected behavior
* All entries should be displayed
### Steps to reproduce
* Go to a window with several entries (more than one page), for stance, Sales Order
* Select the entries by documentNo ( easier to see the problem)
* Remember the last displayed documentNo (let's say 0018)
* Go to page 2
* NOK: The first documentNo on page 2 is 0020

First page: 

![image](https://cloud.githubusercontent.com/assets/16001442/23173055/974c2d76-f860-11e6-8835-9731f840f3bc.png)

Second page:

![image](https://cloud.githubusercontent.com/assets/16001442/23173095/aeb08cd2-f860-11e6-93de-78c0cb9b889e.png)

**Comment by metas-dh** [comment]
Results of IT 1 

tested on w101 / sp80

* still happening for sales orders in w101: NOK
* still happening for bpartners in sp80: NOK

**Comment by teosarca** [comment]
was not rolled out....

**Comment by metas-dh** [comment]
Results of IT 2

tested on w101 

* no entries skipped at the beginning of a page (checked sales orders and sales invoices): OK
