### ISSUE TITLE
Record Limitation for filtering and loading records

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#173]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no limit of opening a window with for example +1.5mio records, This does not make sense for the user. It takes too long to load (approx 16sec) and uses much too high server resources for no significant result.
#### Which are the steps to reproduce?
Open Window 540325 (Product Prices) initially.
### What is the expected or desired behavior?
Allow the definition of record limit per window in the backend. If this limitation is hit, don't load more records and open the window with limit record count. The user can then start filtering correctly to get all wanted data.

![image](https://cloud.githubusercontent.com/assets/13365687/23175868/0f7d8470-f861-11e6-8c57-d81c9e12c9ef.png)

**Comment by teosarca** [comment]
Update: atm i've enforced role's max query limit.

TODO: implement a way to be able to define this limit per Table and/or per Tab.

**Comment by metas-lc** [comment]
IT. OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23173.md

follow-up: https://github.com/metasfresh/metasfresh-webui/issues/180
