### ISSUE TITLE
Attributes editor problems

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#176]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* When openeing the attributes editor from Receipt Schedule, Shipment Schedule (and maybe order lines too, I can't check because of advanced edit bug) the attributes list only contain 3 attributes.
* Values of initial attributes are lost after using this editor
#### Which are the steps to reproduce?
* Create a purchase order for a product that comes with attributes by default
* Complete, go to receipt schedule
* Click on the attributes button.
*NOK: The problems before happen.
### What is the expected or desired behavior?
* All of the attributes should be available for setting/changing.

**Comment by metas-rc** [comment]
![image pasted at 2017-2-22 16-08](https://cloud.githubusercontent.com/assets/16001442/23215867/927f3a6a-f91c-11e6-8633-85c1710748c6.png)
![image pasted at 2017-2-22 16-09](https://cloud.githubusercontent.com/assets/16001442/23215868/93dd04f0-f91c-11e6-9f32-5387efa9d573.png)

**Comment by teosarca** [comment]
NOTE to IT: requires reggression on Swing too!!!

**Comment by metas-rc** [comment]
Results of IT1

* Tested on http://w101.metasfresh.com:8090/

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23176.md OK


I tried it on swing too. The only mention i have is that when opening the ASI Editor in documents that support it ( order lines, inout cands etc) and do not change anything in it, just press ok, you are asked to save the changes. This is not a new thing as far as I know.
