### ISSUE TITLE
Date range parameters are not consistent with the ones I introduce

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#177]
### Is this a bug or feature request?
*Bug
### What is the current behavior?
* The first limit of the range parameter is one day before the date I set in the filter.

#### Which are the steps to reproduce?
* Found while testing https://github.com/metasfresh/metasfresh-webui-frontend/issues/314

* Go to a range date filter criteria (for instance, in SalesOrder, FIlter by Date Ordered)
* Set From: January 3, To: February 1
* =>OK The results are correct. the entries from January 3 till February 1 are displayed but
* NOK: In inspection, I can see that the ValueTo  is actually set as January 2 January 

![image](https://cloud.githubusercontent.com/assets/16001442/23223121/d32af480-f932-11e6-9a3a-6ff0db462822.png)

![image](https://cloud.githubusercontent.com/assets/16001442/23223190/077e584e-f933-11e6-93d0-bf78ae722f6a.png)

### What is the expected or desired behavior?
* The parameters I set should be sent by frontend and received by backend. The algorithm should be changed accordingly.

**Comment by teosarca** [comment]
note to IT: full regression on document filters is needed (webui)

**Comment by teosarca** [comment]
pls test it together with frontend task

**Comment by metas-rc** [comment]
Results of IT1

Tested on http://w101.metasfresh.com:8090

I repeated the test, with January 3 2017 - February 1 2017.

The frontend sent the range the same as before (see screenshot above).
But in response it is changed to January 3 2017, 00:00 - February 1 2017 00:00.

=> I get entries from January 2 2017 .
Please check pic: 

![image](https://cloud.githubusercontent.com/assets/16001442/23263418/da7993fe-f9e6-11e6-894b-fa49d7f3b65c.png)

**Comment by teosarca** [comment]
But @metas-rc  , that's frontend bug. Pls report it there.
Take a look at request payload.

In my case i've picked "2017-01-03".
Frontend sent "2017-01-02T22:00:00.000Z" which makes no sense.
I would expected "2017-01-03T00:00:00.000Z+02:00" to be sent because I am on GMT+2.

**Comment by metas-lc** [comment]
IT: 
sales order, filter for 01.02.2017-01.03.2017
see preview:
value:"2017-02-01T00:00:00.000+01:00"
valueTo:"2017-03-01T00:00:00.000+01:00"
see headers:
value:"2017-02-01T00:00:00.000+02:00"
valueTo:"2017-03-01T23:59:59.999+02:00"

since DateOrdered is type Date and not date+time, in preview it gets converted so it's fine.
Tested other dates in filter - works fine (only those orders are shown)
Filter also remembers what i set last time
checked predefined filter (like yesterday, this month) - works fine
