### ISSUE TITLE
Transforming HU in Handling Unit Editor

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#181]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
No Functionality to Transform existing Handling Units into other Handling Unit/ Packing Instruction Combinations in handling Unit Editor.
#### Which are the steps to reproduce?
Open Handling Unit Editor via Material Receipt. The existing Handling Unit opened cannot be transformed into other combinations.
### What is the expected or desired behavior?
The old functionalities of split and merge shall be combined in one action that can be called via Action menu and takes one selected HU and additional variable action values (existing HU, new HU, new Packing Instruction, Qty to transfer) as Parameter. The Action always reduces the source HU by the given qty and transfers to the target HU (new or existing) with the given qty.

Possible action parms:
a) own Packaging material? If no then it's from the vendor and will be included in the Material receipt.
b) Existing HU (List of HU combinations of needed Level TU, LU depending on source Level)
c) new Packaging Material (List of valid Packaging Material for the given target Level)
d) The quantity that shall be transferred from source to target.

**Comment by teosarca** [comment]
I would suggest to create one action for each use case.
In that way it can be much more clear for everybody.

**Comment by metas-mk** [comment]
As spoken. From a User perspective, I would propose to just have 1 action for these use cases - "transform". The user just wants to change the existing config and should not have to think in advance which action she/ he hast to choose to achieve nearly the same thing bit with slight differences.

Talking about Material Receipt HU Editor here and only about the Use Cases needed there for Transformation. They can be valid for general Handling Unit Editor but are not focussing on those at the moment.
prerequisite: Handling Unit Editor. A Handling Unit line is selected. The selected line can be level CU or TU.

UC1: HU level pure & new (CU:CU, TU:TU) Take out a specific qty from an existing HU and add to new same level HU.
Parameters: a) Selected HU, b) quantity, c0) Flag new CU? c1) Flag new TU? d) Packaging Material List (available HU Packaging Items depending on Level).
Result: --> Decrease the quantities of the selected HU from a) and create an HU (selection from d) planned ) with the given Parameters. The HU is then a new top level HU in the context.

UC2: HU level mixed & new (CU:TU, TU:LU) Take out a specific qty from an existing HU and add to new higher Level HU.
Parameters: a) Selected HU, b) quantity, c1) Flag new TU? c2) Flag new LU? d) Packaging Material List (available HU Packaging Items depending on Level).
Result: --> Decrease the quantities of the selected HU from a) and create an HU (selection from d) planned ) with the given Parameters. The HU is then a new top level HU in the context.

UC3: HU level mixed & new (CU:TU, TU:LU) Take out a specific qty from an existing HU and add to new higher Level HU.
Parameters: a) Selected HU, b) quantity, c1) Flag new TU? c2) Flag new LU? d) Packaging Material List (available HU Packaging Items depending on Level).
Result: --> Decrease the quantities of the selected HU from a) and create an HU (selection from d) planned ) with the given Parameters. The HU is then a new top level HU in the context.

**Comment by metas-lc** [comment]
IT: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23181.md
