### ISSUE TITLE
Material Receipt w/ multiple lines and solitary CU Buckets

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#182]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
The user can only select 1 row at a time for material receipt.
#### Which are the steps to reproduce?
Open Material Receipt Candidates window and select more than 1 line. Not possible. No actions active.
### What is the expected or desired behavior?
The user must be able to select more than 1 line and do a Material Receipt. In this case, the main actions w/ predefined Packaging Material and combinations are deactivated. The user selects a special multiple lines/ manual packaging action. The Handling Units are created as Virtual PI (Empty Packaging) Buckets w/ CU Level or solitary CU Level lines. These have the whole remaining qty of the selected lines.

**Comment by teosarca** [comment]
Note to IT:
* pls test the whole workflow (from receipt schedule to HUs, receive, reverse)
* regression needed

**Comment by metas-lc** [comment]
IT:
* receive HUs multilines works fine (if different bpartners you get different inouts. Else they get on the same inout). If qtytomove = 0 then it won't do anything. OK
* regression: tested attributes (they propagate fine), hu assignments, receipt shedule allocation, reversing inouts, receiving multiple LUs (with save) OK
* quality discount NOK. Created task: https://github.com/metasfresh/metasfresh-webui/issues/194
