### ISSUE TITLE
When parsing JSON dates (without time) always ignore the timezone

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#183]
Note to IT:
To be tested when https://github.com/metasfresh/metasfresh-webui-frontend/issues/419 is done.
And mainly u just need to check the test cases of  https://github.com/metasfresh/metasfresh-webui-frontend/issues/406 .

**Comment by teosarca** [comment]
Update: changed the endpoint to provide the timezone in ISO8601's format, i.e. +/-hh:mm

**Comment by teosarca** [comment]
NOTE to IT: full regression on all Date and DateTime fields is required!!!

**Comment by metas-lc** [comment]
IT: wait for https://github.com/metasfresh/metasfresh-webui-frontend/issues/406

**Comment by metas-lc** [comment]
created the following tasks related with Dates:
https://github.com/metasfresh/metasfresh-webui-frontend/issues/469
https://github.com/metasfresh/metasfresh-webui-frontend/issues/470
https://github.com/metasfresh/metasfresh-webui-frontend/issues/471
https://github.com/metasfresh/metasfresh-webui-frontend/issues/472

Rest seems fine (documents dates, dates+time and filtering)
