### ISSUE TITLE
Documents shall automatically have a default value for standard fields

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#187]

**Comment by teosarca** [comment]
NOTE to IT: full webui regression is needed

**Comment by metas-lc** [comment]
IT
- tested with creating new documents: default fields like doctype, org, date and currency were set by default OK
- tested with new org - login with new org and create a new document => the new org is set OK
- tested new entries in tables like Product - default fields (like org) are set. Used "Add new" and works there too (e.g. org and uom are set) 
- regression test worked fine
