### ISSUE TITLE
Field's mandatory flag is not considered

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#188]
### Is this a bug or feature request?
bug

### What is the current behavior?
If the field is configured as:
* IsMandatory: true
* MandatoryLogic: null
=> field is considered not mandatory

### What is the expected or desired behavior?
Field shall be considered mandatory in that case

**Comment by teosarca** [comment]
NOTE to IT: full webui regression is needed

**Comment by metas-lc** [comment]
All looks fine, besides an issue in orderline - created follow-up https://github.com/metasfresh/metasfresh-webui/issues/215
other issues like, you can create a new bpartner or cu-tu in product with mandatory fields not filled, we have https://github.com/metasfresh/metasfresh-webui-frontend/issues/437
