### ISSUE TITLE
"Not saved yet" info in REST-API

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#191]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently no, or only debug information is existing via Rest-API for windows about the save status (saved, not saved).
#### Which are the steps to reproduce?
Check any sample window.
### What is the expected or desired behavior?
Provide data about the save status, so the frontend can react on that and display this information to the user.

**Comment by metas-mk** [comment]
Linked to Frontend Issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/437

**Comment by teosarca** [comment]
Note to IT: to be tested when frontend task is done

**Comment by metas-mk** [comment]
Tested w/ Product window. Initially saved status: false. Edited 2 mandatory fields (1 remaining untouched). saved status: false. edited the remaining mandatory field, saved status: true.
Works as required. Won't wait for frontend task. Can be tested independently. 
Closed and moved to done.
