### ISSUE TITLE
Restrict when allowing to create a new included document

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#195]
i.e. don't allow creating a new included document when:
* parent document is new
* there is another included document which is new

**Comment by metas-rc** [comment]
Results of IT1

Tested on https://w101.metasfresh.com:8443

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-195-webui.md OK

Followups for some frontend problems: 
https://github.com/metasfresh/metasfresh-webui-frontend/issues/450
https://github.com/metasfresh/metasfresh-webui-frontend/issues/450
