### ISSUE TITLE
KPI master data shall provide to frontend a recommended refresh interval

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#199]
![image](https://cloud.githubusercontent.com/assets/1244701/23560255/729f2246-0042-11e7-90ec-14ba62b80134.png)

![image](https://cloud.githubusercontent.com/assets/1244701/23560285/934fe5d4-0042-11e7-83be-73de86a0556d.png)

**Comment by metas-lc** [comment]
IT: 
- changed polling interval on KPI, checked swagger: my change was there. OK
