### ISSUE TITLE
Generic "add new" search field functionality

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#200]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
In WebUI in autocomplete search fields, we have a new button at the bottom of the list. The user can select the new button to create new Master data on the fly. Until now there is no functionality behind the new button.

#### Which are the steps to reproduce?
For example Open Sales Order window. In Business Partner Field type Name that does not exist. Press on dropdown "new Business partner". A modal overlay opens.

### What is the expected or desired behavior?
After pressing "new ..." a modal overlay opens w/ the Window that belongs to the field ID in "new mode. The user can edit the content and dan create a new record. When pressing done, the ID is transferred back to search field in the main window and the user can proceed w/ entering data.

Issue belongs to https://github.com/metasfresh/metasfresh-webui-frontend/issues/126

**Comment by teosarca** [comment]
Note to IT: to be tested when frontend task is done

**Comment by teosarca** [comment]
Closing this one because work continued on https://github.com/metasfresh/metasfresh/issues/1090

**Comment by metas-dh** [comment]
Moving to done since both metasfresh-webui-frontend/issues/126 and metasfresh/metasfresh#1090 were tested successfully.
