### ISSUE TITLE
Deleting header document not working

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#202]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Deleting header document is kind of not happening.

#### Which are the steps to reproduce?
Create an order and fill the bpartner, so it will be saved for sure.
Now, pls copy the current URL to your clipboard.
Delete the order. You are forwarded to orders view.
Call the URL you have copied.
Document is displayed => NOK. An error is expected because the document shall not exist.

### What is the expected or desired behavior?
Delete is delete.

**Comment by metas-rc** [comment]
Results of IT1

Tested on https://w101.metasfresh.com:8443

Followed the steps to reproduce. When I called the URL I only saw the white main page with nothing in it.
In inspection I have: 

> "Not Found"
> exception
> :
> "de.metas.ui.web.window.exceptions.DocumentNotFoundException"
> message
> :
> "No document found for /W143/1004066"
> path
> :
> "/rest/api/window/143/1004066"
> status
> :
> 404
> timestamp
> :
> 1488536992816

Additional frontedn problems to be solved in: 
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/462
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/477
