### ISSUE TITLE
can't complete order when m_attributesetinstance_id is null

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui#215]
### Is this a bug or feature request?
bug
### What is the current behavior?
can't complete order when m_attributesetinstance_id is null
#### Which are the steps to reproduce?
1. go to sales order and create a new one
2. add a product
3. right click on orderline, advanced edit
4. remove the product, ok, then add it back
=> notice that m_attributesetinstance_id is null
5. complete the order: 
=> error message that Invalid('M_AttributeSetInstance_ID is mandatory.') NOK
### What is the expected or desired behavior?
i should be able to complete the order

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

* repeated testcase, still get the error message that Invalid('M_AttributeSetInstance_ID is mandatory."): NOK
(product was on pricelist w/ and w/o attribute)

**Comment by metas-dh** [comment]
Results of IT 2
tested on w101

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23215.md: OK
