### ISSUE TITLE
new entry in documents

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui#217]
### Is this a bug or feature request?
bug/ feature
### What is the current behavior?
i can create new receipt cands, shipment cands, receipt and shipments, but i can't save/complete them because there are mandatory fields which are empty and readonly (e.g. doctype).
#### Which are the steps to reproduce?
new receipt candidate/ new shipment candidate / new shipment / new receipt
add all editable and mandatory fields, complete => you can't because some mandatory fields are readonly
### What is the expected or desired behavior?
to not be able to add new entry when we don't want to

**Comment by teosarca** [comment]
New in Receipt candidates and Shipment candidates shall be disallowed, like on Swing, but it's not.
Fixed in #221

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

* create new shipment candidates & receipt candidates: not possible anymore, OK
* doctype in manual shipment is editable: OK
* setting doctype in manual shipment creates the doc no.: OK

problens:
* doc no. in manual material receipts can be set manually, any no. or name user likes: NOK, => #240
* manual shipment: error when adding product bc of missing DateOrdered, but can be completed nevertheless: NOK, => #241
* manual shipment: when adding a product in product window, qty & qtyTU is not editable: imho NOK, but it's the same in swing
