### ISSUE TITLE
too many work packages in shipment candidates when creating shipment

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui#219]
### Is this a bug or feature request?
bug
### What is the current behavior?
cannot make sales inouts from shipment candidate and we get 80 work packages when in single view
#### Which are the steps to reproduce?
1. create 1 (or multiple) sales order, complete
2. go to referenced documents and select shipment candidates
3. double click on the line to see it in single view
4. go to auswahl liefern, press start
=> "Erstellt: 80 WorkPackage Queue; Überspringe 0"
=> no shipment created
### What is the expected or desired behavior?
to enqueue only my selection, and to create a shipment

![io1](https://cloud.githubusercontent.com/assets/16001666/23619564/ba0627c2-029c-11e7-8a87-c9234403dc89.png)

![io2](https://cloud.githubusercontent.com/assets/16001666/23619568/bd3d6d9c-029c-11e7-9eab-ce7a4f5e85d2.png)

**Comment by teosarca** [comment]
Note to IT:
* pls do the regression testing for processes called from single document, also printing single document

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

* in shipment schedule of a newly created sales order, single view, go to auswahl liefern, press start: 
=> "Erstellt: 1 WorkPackage Queue; Überspringe 0": OK
=> but no shipment created: NOK

* shipment was also not created from grid view!

**Comment by metas-dh** [comment]
Results of IT 2
tested on w101

* in shipment schedule of a newly created sales order, single view, go to auswahl liefern, press start:
   => "Erstellt: 1 WorkPackage Queue; Überspringe 0": OK
   => shipment created: OK (problem before was product type)

* shipment was also created from grid view, 1 WorkPackage Queue: OK

**Comment by teosarca** [comment]
@metas-dh do u know what's changed between IT1 and IT2?

**Comment by metas-dh** [comment]
The product category of the product i tested with was changed: Convenience Salat; used to have category Artikel, but was set to category Erfolgskonten, for whatever reason: products with that category don't get shipped (same problemas in  #1127). After updating the category back to Artikel, the shipment was created without problems.
