### ISSUE TITLE
Receipt Candidates - Foto process is not attaching the picture

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#225]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* open receipt candidates
* select one
* take a Foto
* check the attachements => NOT attached

### What is the expected or desired behavior?
Foto shall be attached and shall be visible in Menu-Attachments.

**Comment by teosarca** [comment]
Current status:
* the picture it's "attached" as an AD_Archive which contains the picture in a PDF

Required changes:
* attach the picture as a true attachment (i.e. AD_Attachment) and don't convert it to PDF
* TODO: Implement filesystem attachment which would really work for Swing too  - https://github.com/metasfresh/metasfresh/issues/1111

**Comment by teosarca** [comment]
UPDATE: talked with Mark and we decided to create AD_Archives instead of AD_Attachments but we shall implement  #227

**Comment by metas-mk** [comment]
Tested. Works as required.
