### ISSUE TITLE
QuickInput BPartner not updating BPartner after new done

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#230]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When using QuickInput BPartner, creating a new Business Partner, finishing edit & Done, the BPartner Name is not updated in Document Input Field for Partner.
#### Which are the steps to reproduce?
Create a Sales Order and create new BusinessPartner on the Fly w/ QuickBPartner Input.
### What is the expected or desired behavior?
Update the newly created Business Partner name in Input Field of Sales Order.

![image](https://cloud.githubusercontent.com/assets/13365687/23669971/6c812b76-0366-11e7-8e77-59ffa0541ae0.png)

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23230.md: OK
