### ISSUE TITLE
Remaining TU Qty in Receive HUs window

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui#236]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
When opening the window Receive HUs, the qty TU is the max qty of this type of TU for an LU, no matter if you have not received anything yet or already made a partial receipt.
#### Which are the steps to reproduce?
* Create a purchase order with a high qty of TUs
* in receipt schedules, open the window Receive HUs: max qty of TU is displayed for TUs
* create a partial receipt, so a smaller qty of TUs remains
* open the window Receive HUs again: still max qty of TU is displayed for TUs
### What is the expected or desired behavior?
When receiving the Products then show the remaining Qty of TUs:
a) If the remaining qty is > 0 and less than a full palette --> show the remaining Qty
b) If the remaining qty is > 0 and more or equal than a full palette --> show the max qty of palette (like now)
c) If the remaining qty is = 0 --> show the max qty of palette (like now)
=> should work the same as in Remaining TU Qty in Quickaction and HU Config #228

**Comment by metas-mk** [comment]
Tested. Works nicely. Closing.
