### ISSUE TITLE
Breadcrumb Navigation Plural caption

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#24]
Possibility to allow Plural Caption via breadcrumb navigation.

  {
                    "nodeId": "129",
                    "caption": "Sales Order",
                    "captionPlural": "Sales Orders",
                    "modeNew": true,
                    "modeBrowse": true,
                    "type": "window",
                    "elementId": 143
                },
                {
                    "nodeId": "130",
                    "caption": "Order Candidate",
                    "captionPlural": "Order Candidates",
                    "modeNew": false,
                    "modeBrowse": true,
                    "type": "window",
                    "elementId": 144
                },

shall lead to example ...
menu/ sales management/ sales orders (plural caption for grid view)
menu/ sales management/ sales order/123456 (single caption for detail view of specific order)

**Comment by teosarca** [comment]
UPDATE:
In AD_Menu i've introduced WEBUI_NameBrowse and WEBUI_NameNew.

In JSONMenuNode i've just introduced a new property called "captionBreadcrumb.

The mapping between metasfresh applicaton dictionary and JSON is:
* AD_Menu.Name --> "captionBreadcrumb"
* AD_Menu.WEBUI_NameBrowse ---> caption, if type=window
* AD_Menu.WEBUI_NameNew --> caption, if type=newRecord
