### ISSUE TITLE
Support for custom order bys in browseView

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#27]

**Comment by teosarca** [comment]
UPDATE: introduced "orderBy" parameter to GET /rest/api/window/view/{viewId} endpoint.

The "orderBy" format is: command separated field names. Use +/- prefix for ascending/descending.
e.g. +C_BPartner_ID,-DateOrdered

**Comment by metas-dh** [comment]
Results of IT 1  

http://nextgen.metasfresh.com

sales orders: 
* order by overall sum, descending / Bereitstellungsdatum ascending: flip through pages, back and forth: order is still set at the top, but the sales orders are not ordered correctly: NOK
