### ISSUE TITLE
Required parameter, similar to mandatory.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui#42]
In filters, we are using the same widgets as normal, in documents. In my opinion required parameter in filter params has exactly the same purposes as mandatory in window layouts. Can we just replace required by mandatory in filters? It will be more optimally and unified. (ps. and it will automatically apply extra styles to fields and colour as required field).

It will partially fix the https://github.com/metasfresh/metasfresh-webui-frontend/issues/78

**Comment by cadavre** [comment]
I believe it's all about changing parameter name from "required" to "mandatory". Keep things unified and will work from zero time on. :)

**Comment by damianprzygodzki** [comment]
@teosarca is it done?

**Comment by damianprzygodzki** [comment]
I've seen that yes. Btw. now required param is not used.

**Comment by teosarca** [comment]
Thanks @damianprzygodzki .
... then i will remove the required param soon...
