### ISSUE TITLE
Initial Setup of KPI with elk stack

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#48]
Initial Setup of KPI for WebUI dashboard with elk stack.
First rough ideas:
1) Top 5 customers sales/ week (€ Sum) --> Barchart
2) Top 5 products sales/ week (€ Sum) --> Barchart
3) Top 5 counties sales/ week (€ Sum) --> Barchart
4) Top 5 product categories sales/ week (€ Sum) --> Barchart
5) Top 5 salesrep sales/ week (€ Sum) --> Barchart or other
6) Sales sum this week (€ Sum, red, yellow, green) --> Gauge or other
7) Orderlines per Order Week (% Qty) --> Piechart, Donut or other
8) Top 5 orderlines creatory Week (Qty Sum) --> Barchart or other
9) Ordered Packing Material Week (% Qty) --> Piechart, Donut or other
10) Orderlines Trend Week compared last week (Qty Sum) --> Lines or other

**Comment by metas-mk** [comment]
Started an initial setup based on orderlines search index.

**Comment by teosarca** [comment]
I think everything was fulfilled on this task, so i am closing it now.

**Comment by metas-dh** [comment]
tested by mk on w101, OK
