### ISSUE TITLE
Provide widget type in API responses, along with the field value

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#49]

**Comment by teosarca** [comment]
NOTE: this task was requested by @damianprzygodzki in order to fix some issues on date picker.

It might be related with:
https://github.com/metasfresh/metasfresh-webui-frontend/issues/75

**Comment by damianprzygodzki** [comment]
As far as it is now, it is great, and it is starting working properly. But the type appeared only in data endpoint, could we provide the same in responses from commits?

**Comment by teosarca** [comment]
@damianprzygodzki  done. will be available on next rollout
