### ISSUE TITLE
Backend support for grid view actions

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#50]
Required by https://github.com/metasfresh/metasfresh-webui-frontend/issues/100

**Comment by teosarca** [comment]
Following endpoints were introduced/changed:
* new: GET /rest/api/documentView/{viewId}/actions - get the available document actions for a given viewId

* deprecated: PUT /rest/api/process/instance

* new: POST /rest/api/process/instance - create a new process instance. The body format is:
```
{
  // mandatory processId
  "processId": 0,

 // fill it when you call it from a particular document. e.g. documentType=143, documentId=1000123
  "documentType": "string",  //
  "documentId": "string",

// fill it when you call it from a grid view. The "viewDocumentIds" is optional (only if user selected something).
  "viewId": "string",
  "viewDocumentIds": [
    ...
  ]
}
```

**Comment by damianprzygodzki** [comment]
Shouldn't we have a one unified endpoint to get available actions? 
Because the new one is only for gridview, we got already one for windowType/documentId. What about have one for windowType?

**Comment by teosarca** [comment]
> Because the new one is only for gridview, we got already one for windowType/documentId. What about have one for windowType?

Agree, basically we shall the window endpoints make them more RESTish.

But we shall have different endpoints for "particular document" and "grid view" actions, because the parameters are completely different.
