### ISSUE TITLE
Fastlane Login without Dashboard

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#60]
Fastlane Login without Dashboard
- possibility to have a fastlane per User Setting which does not open the Dashboard after Login, 
- this could be switchable in Dashboard configuration. shall have an url to this default page. shall open an empty window with header and metasfresh Logo in that case.
- add a link/ button on that page to open dashboard

**Comment by teosarca** [comment]
everything was done on https://github.com/metasfresh/metasfresh-webui-frontend/issues/199

**Comment by metas-rc** [comment]
Results of IT 1: 
Tested on http://w101.metasfresh.com:8090
Whenlogging into webui, one does not  directly see the darboard options, but only the metasfresh logo. For seeing the dashboard, the Home button must be pressed.
