### ISSUE TITLE
Included Tabs with no ParentID error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#62]
Included Tabs with no ParentID error
- see all windows with Handling unit assignment
![image](https://cloud.githubusercontent.com/assets/13365687/20622022/4b17c1e4-b301-11e6-95d9-8a49f729a35f.png)

**Comment by teosarca** [comment]
NOTE to dev: to be fixed in de.metas.ui.web.window.descriptor.factory.standard.GridTabVOBasedDocumentEntityDescriptorFactory.extractParentLinkColumnName(GridTabVO, GridTabVO)

**Comment by teosarca** [comment]
https://github.com/metasfresh/metasfresh-webui/commit/a30fc76fd7fe6500ce27900a36968c455e67d269
