### ISSUE TITLE
Fast line entry widget in subtabs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#65]
Fast line entry widget in included tabs
- possibility to have one or more dependent fields for quick line creation (generic)
- fields shall be shown in head area of included tab (e.g. order line)
- user can conmpletely use this quickentry with keyboard

**Comment by metas-lc** [comment]
IT: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%2365.md OK
