### ISSUE TITLE
Error when introducing parameters to report

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#67]
![image](https://cloud.githubusercontent.com/assets/16001442/20674573/275814a0-b592-11e6-98b0-1383298aabf8.png)

Steps to reproduce (example)
* Go to Partner, select a row
* Open the available processes
* Run the process "Preisliste"
* Click to select a parameter. 
 => NOK: You will see an error like in the picture attached to the task.

Stacktrace : http://pastebin.com/VNd05yi3

**Comment by teosarca** [comment]
Fixed for Preisliste report: https://github.com/metasfresh/metasfresh/commit/6bafbb9ba9ed74191a7af1cca9a52b1b8a68766b

**Comment by metas-rc** [comment]
I found the problem in another place: 
* Create a new sales order
* Go to Vertragsbedingungen field and press:
=> NOK: error shown. See stacktrace: http://pastebin.com/NC5CyCrd

**Comment by teosarca** [comment]
@metas-rc fixed:
https://github.com/metasfresh/metasfresh/commit/9b6c87df4659b41623779bc2addf9163afc1e798
https://github.com/metasfresh/metasfresh/commit/fbef9ad787c8f9bba29d8bdc2a7f306cdf5bc667

**Comment by metas-dh** [comment]
Results of IT 1  

* http://w101.metasfresh.com:8090/

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-932.md: OK
