### ISSUE TITLE
Error message when pressing "IsManual" in Invoice Candidates

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#68]
![webui_invoicecandidate_ismanual](https://cloud.githubusercontent.com/assets/16001442/20705634/6304ff96-b62c-11e6-9319-9f841381d3f8.png)

Steps to reproduce:
* Go to an INvoice candidate
* Fress flag IsManual
 => NOK: Error displayed as in the picture above

Stacktrace: http://pastebin.com/mSnk5cVH

**Comment by teosarca** [comment]
Fixed by https://github.com/metasfresh/metasfresh/commit/9f719e339ac464836bb1fbd3d27dda2cbda3b573
