### ISSUE TITLE
Add BPLocation Error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#70]
Add BPLocation in WebUI leads to the following error:

![image](https://cloud.githubusercontent.com/assets/13365687/20709808/a6984726-b637-11e6-9508-972075da6f7e.png)

**Comment by metas-dh** [comment]
Results of IT 1  

http://w101.metasfresh.com:8090

* no more error popping up when clicking "Add new" button for new address: OK
* window for adding a new report opens up: OK
* new address can not be added yet, will be done in https://github.com/metasfresh/metasfresh-webui-frontend/issues/122: OK
