### ISSUE TITLE
Fix Inout Callouts

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#73]
I tried to create a manual inout and had problems with several fields.
ATM the manual Shipment is not required but we plan to support Reactivation / Completion of shipments and the callouts need to be fixed because of this.

Example of fields I had problems with: 
In shipment:
*  BPartner
* Document Type

Other problems I found with Shipments ( will put pastes from the Inspector) 

*inout warehouse
*inoutline product

LookupValue$IntegerLookupValue cannot be cast to java.lang.Integer"
path
:
"/rest/api/window/commit"

* inoutline product: 
{timestamp: 1480433773918, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"de.metas.ui.web.window.exceptions.DocumentFieldNotFoundException"
message
:
"Field M_HU_PI_Item_Product_ID was not found in Document{id=1000161, NEW=true, windowNo=32, writable=false, valid=Invalid('Mandatory field not filled: DocumentNo'), saveStatus=DocumentSaveStatus{hasChangesToBeSaved=true, error=false, reason=Invalid status: Invalid('Mandatory field not filled: DocumentNo')}}"
path
:
"/rest/api/window/dropdown"
status
:
500
timestamp
:
1480433773918

* inoutline,manual Packing Material = true
* set diff packing instrucitons: 

{timestamp: 1480433931287, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.ad.expression.exceptions.ExpressionEvaluationException"
message
:
"@NotFound@: DateOrdered"
path
:
"/rest/api/window/dropdown"
status
:
500
timestamp
:
1480433931287

**Comment by teosarca** [comment]
Fixed/refactored the CalloutInOut: https://github.com/metasfresh/metasfresh/commit/5ed1b81ca4409e9488b5a4ca532160053e84f1e4

**Comment by teosarca** [comment]
NOTE to IT:
* full regression test on Shipment and Material receipt windows
* full regression on Sales/Purchase Order windows
* full regresion on DD Order window
