### ISSUE TITLE
Fix BP Relation process 

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#80]
1)
* Go to BPartner 
* Select the action for BP relation creation process
* set BPartner and BPartner relation parameters
* Start the process
*=> NOK: there is no warning about setting the location parameters, even if they are mandatory
*=> NOK: I get the following error: http://pastebin.com/Cr7DNctt (note: I selected different partners)

2)
* Go to BPartner 
* Select the action for BP relation creation process
* set BPartner and BPartner relation parameters, also set the locations
* Uncheck the flag "isBillTo"
* Run the process
* => NOK: I get the following error: http://pastebin.com/bdUBc0Fm
Even if the flag was set on false ( [{field: "IsBillTo", value: false, widgetType: "YesNo"}] - from Inspection) it is true if you search for the process parameter (select * from AD_PInstance_Para where AD_PInstance_ID= [your ad_pinstance_id])

**Comment by metas-rc** [comment]
Note: Sometimes it works!

**Comment by teosarca** [comment]
UPDATE: fixes on backend
* bugfix: boolean params were not saved
* hotfix: when trying to start a process which have some missing mandatory params, at least throw an exception

NOTE: the mandatory parameters are not enforced on frontend.
see https://github.com/metasfresh/metasfresh-webui-frontend/issues/141
