### ISSUE TITLE
Favicon for pdf Tab

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#81]
Favicon for pdf Tab.
metasfresh Favicon for pdf Tab needed. atm there is a favicon with a leaf.
![image](https://cloud.githubusercontent.com/assets/13365687/20963908/adb15cda-bc6f-11e6-9964-64cbbd10e1d2.png)

**Comment by teosarca** [comment]
Related with https://github.com/metasfresh/metasfresh-webui/issues/59

**Comment by teosarca** [comment]
NOTE: when testing, it might be you will need to reset your browser cache.
