### ISSUE TITLE
Receipt Schedules create before Purchase Order being completed

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui#84]
Steps to reproduce: 
* Create a purchase order 
* Add several lines for different products
* Go to Referenced Documents ( do not complete the order before)
=>NOK: Receipt Schedules created. 

The receipt schedules should only be created after the order is completed
I tried on the swing version of w101 and it works fine. The bug is webui only.

**Comment by metas-rc** [comment]
Until now I only found these in the console: 

client: http://pastebin.com/fDgjLRgK

server : http://pastebin.com/AHXEhjmE

**Comment by teosarca** [comment]
took a quick look, those are not relevant.

**Comment by teosarca** [comment]
the fix shall be at least in de.metas.inoutcandidate.modelvalidator.C_OrderLine_ReceiptSchedule.createReceiptSchedules(I_C_OrderLine)

where we shall check if the order is not Drafted.


@metas-rc But this is not a metasfresh-webui bug but a metasfresh bug. Pls reported there and describe the steps to reproduce ;)

**Comment by metas-rc** [comment]
This is not a webui issue. Created a new one on metasfresh: https://github.com/metasfresh/metasfresh/issues/688
