### ISSUE TITLE
Adjust DocAction Names

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#89]
Adjust the DocAction names. Now that they are a real action and we the status on button and next action in dropdown, we should reduce the action names back to "complete", "void" ... without "processing"
![image](https://cloud.githubusercontent.com/assets/13365687/21089818/7b2d8caa-c03b-11e6-953c-15acc622f87f.png)

**Comment by teosarca** [comment]
@metas-mk  i think that's a translation issue which shall go to metasfresh project. wdyt?

**Comment by metas-mk** [comment]
Agree. Will provide the migration script there and join to this issue.

**Comment by teosarca** [comment]
was tested by @metas-rc 
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-1006.md
