### ISSUE TITLE
WebUI Sales Order Window tweaks

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#93]
WebUI Sales Order Window tweaks
Grid view:
- shall show the following fields (Doctype, docno, dateordered, docstatus, BPartner name, location, poreference, datepromised, warehouse, organisation)

Detail view:
- shall show the POReference

**Comment by teosarca** [comment]
also pls take out Gebinde field from order lines

**Comment by metas-mk** [comment]
@teosarca done. I took it out of combined product ID Field.

**Comment by metas-dh** [comment]
Successfully tested by mk.
