### ISSUE TITLE
Dashboard breadcrumb menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#95]
Dashboard Breadcrumb Menu wrong since last rollout.
Shows Home + last path with concatenated "/Dashboard". Should be Home"/ Dashboard". Further on, if you press on breadcrumb then you cannot navigate.

![image](https://cloud.githubusercontent.com/assets/13365687/21142074/bd9e77b0-c140-11e6-8779-6d5251e7c9b7.png)

**Comment by teosarca** [comment]
frontend issue.
