### ISSUE TITLE
Exception error messages are not parsed, so they are not translated

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui#98]
e.g.
![image](https://cloud.githubusercontent.com/assets/1244701/21225916/e70ff866-c2db-11e6-85a7-c19ccc3a4bf9.png)

Reason:
Atm we are using DefaultErrorAttributes, and in method addErrorMessage(...) we have at line ~137:
`errorAttributes.put("message", error.getMessage());`

Solution:
* write a custom HandlerExceptionResolver/ErrorAttributes which shall call error.getLocalizedMessage()

**Comment by metas-lc** [comment]
IT https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%2398.md OK
